apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod 
spec: 
  containers:
    - name: alpine
      image: alpine:3.15.0
      ports:
        - containerPort: 80
          protocol: TCP
      command: ["sleep"]
      args: ["1d"]