apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata:
      labels: 
        app: nginx
        version: 1.21
    spec: 
      containers: 
        - name: nginx
          image: nginx:1.21
          ports: 
            - containerPort: 80
              protocol: TCP