apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc 
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 2Gi
  storageClassName: managed-premium
---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec: 
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - name: mysql
          containerPort: 3306
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: qtdevops
        - name: MYSQL_DATABASE
          value: qtecommerce
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: qtdevops
      volumeMounts: 
        - name: mysql-vol
          mountPath: "/mysql"
          readOnly: true
  volumes: 
    - name: mysql-vol
      persistentVolumeClaim:
        claimName: pvc


-----------------------------------------------------
