apiVersion: v1  
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts: 
        - name: secret-volume
          mountPath: "/secret"
          readOnly: true
  volumes: 
    - secret: 
        secretName: secret
        items: 
          - key: "name"
            path: "name"
      name: secret-volume