apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec: 
  containers:
    - envFrom: 
        - configMapRef: 
            name: demo-configmap
      image: nginx:1.21.5
      name: nginx
      volumeMounts: 
        - mountPath: /configmap
          name: configvolume
          readOnly: true
  volumes:
    - configMap: 
        name: demo-configmap
      name: configvolume

---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec: 
  containers:
    - name: nginx
      image: nginx:1.21.5
      env: 
        - name: EDUCATION
          valueFrom: 
            configMapKeyRef: 
              name: demo-configmap
              key: education
        - name: AGE
          valueFrom: 
            configMapKeyRef:
              name: demo-configmap
              key: age
      volumeMounts: 
        - name: configmap-volume
          mountPath: "/config"
          readOnly: true
  volumes: 
    - name: configmap-volume
      configMap: 
        name: demo-configmap
        items:
          - key: "age"
            path: "age"
          - key: "mental.characteristics"
            path: "mental.characteristics"