---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: demo-configmap
data: 
  physical.properties:  |
    height=5.10
    weight=90
    colour=white
    hair.colour=black
  mental.characteristics:  |
    iq=1
    eq=2
  education: b.tech
--- 
apiVersion: v1
kind: Pod
metadata: 
  name: alpine
spec: 
  containers:
    - args:
        - sleep 1d
      env: 
        - name: demo-env
          valueFrom: 
            configMapKeyRef:
              name: demo-configmap
      volumeMounts: 
        - name: config-volume
          mountPath: /config
          readOnly: true
  volumes: 
    - name: config-volume
      configMap:
        name: demo-configmap
      

