apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
spec: 
  containers:
    - name: nginx
      image: nginx:1.21.5 
      volumeMounts: 
        - name: cache-volume
          mountPath: /cache
  volumes: 
    - emptyDir: {}
      name: cache-volume


  ---------------------------

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
spec: 
  containers:
    - name: nginx
      image: nginx:1.21.5 
      volumeMounts: 
        - name: test-volume
          mountPath: /test-ebs
  volumes: 
    - awsElasticBlockStore: 
       fsType: ext4
       volumeID: *******
       name: test-volume